exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "build",
    "buck-out",
    "dist",
    "docs",
    "node_modules",
    "venv",
]

line-length = 88
indent-width = 4
target-version = "py39"

[lint]
select = [
    "E",
    "F",
    "UP",
    "ANN",
    "ASYNC",
    "S",
    "B",
    "COM",
    "C4",
    "LOG",
    "PIE",
    "RET",
    "SIM",
    "ARG",
    "PTH",
    "T20",
    "YTT",
    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",
    "N",
    "C90",
    "PL",
    "ERA",
    "FAST",
    "RUF",
    "FURB",
]

ignore = [
    "E501",
    "B006",
    "ANN401",
    "COM812",
    "PLR0913",
    "PLR2004",
]

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"**/tests/**/*.py" = ["S101"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
